/** api calls for job item */
export const FETCH_JOBS = {
  SUCCEEDED: 'JOB_API_FETCH_JOBS_SUCCEEDED',
  FAILED: 'JOB_API_FETCH_JOBS_FAILED',
}

export const CREATE = {
  SUCCEEDED: 'JOB_API_CREATE_SUCCEEDED',
  FAILED: 'JOB_API_CREATE_FAILED',
}

export const REMOVE = {
  SUCCEEDED: 'JOB_API_REMOVE_SUCCEEDED',
  FAILED: 'JOB_API_REMOVE_FAILED',
}

/** fetch config only (no client specific props) */
export const FETCH_CONFIG = {
  SUCCEEDED: 'JOB_API_FETCH_CONFIG_SUCCEEDED',
  FAILED: 'JOB_API_FETCH_CONFIG_FAILED',
}

export const UPDATE = {
  SUCCEEDED: 'JOB_API_UPDATE_SUCCEEDED',
  FAILED: 'JOB_API_UPDATE_FAILED',
}

export const SET_READONLY = {
  SUCCEEDED: 'JOB_API_SET_READONLY_SUCCEEDED',
  FAILED: 'JOB_API_SET_READONLY_FAILED',
}

export const UNSET_READONLY = {
  SUCCEEDED: 'JOB_API_UNSET_READONLY_SUCCEEDED',
  FAILED: 'JOB_API_UNSET_READONLY_FAILED',
}

export const START = {
  SUCCEEDED: 'JOB_API_START_SUCCEEDED',
  FAILED: 'JOB_API_START_FAILED',
}

export const STOP = {
  SUCCEEDED: 'JOB_API_STOP_SUCCEEDED',
  FAILED: 'JOB_API_STOP_FAILED',
}

export const FETCH_CONTAINER_JOBS = {
  SUCCEEDED: 'JOB_API_FETCH_CONTAINER_JOBS_SUCCEEDED',
  FAILED: 'JOB_API_FETCH_CONTAINER_JOBS_FAILED',
}
