
/** api calls for job item */
export const CREATE = {
  REQUESTED: 'JOB_API_CREATE_REQUESTED',
  SUCCEEDED: 'JOB_API_CREATE_SUCCEEDED',
  FAILED: 'JOB_API_CREATE_FAILED',
}

export const REMOVE = {
  REQUESTED: 'JOB_API_REMOVE_REQUESTED',
  SUCCEEDED: 'JOB_API_REMOVE_SUCCEEDED',
  FAILED: 'JOB_API_REMOVE_FAILED',
}

/** fetch config only (no client specific props) */
export const FETCH_CONFIG = {
  REQUESTED: 'JOB_API_FETCH_CONFIG_REQUESTED',
  SUCCEEDED: 'JOB_API_FETCH_CONFIG_SUCCEEDED',
  FAILED: 'JOB_API_FETCH_CONFIG_FAILED',
}

export const UPDATE = {
  REQUESTED: 'JOB_API_UPDATE_REQUESTED',
  SUCCEEDED: 'JOB_API_UPDATE_SUCCEEDED',
  FAILED: 'JOB_API_UPDATE_FAILED',
}

export const SET_READONLY = {
  REQUESTED: 'JOB_API_SET_READONLY_REQUESTED',
  SUCCEEDED: 'JOB_API_SET_READONLY_SUCCEEDED',
  FAILED: 'JOB_API_SET_READONLY_FAILED',
}

export const UNSET_READONLY = {
  REQUESTED: 'JOB_API_UNSET_READONLY_REQUESTED',
  SUCCEEDED: 'JOB_API_UNSET_READONLY_SUCCEEDED',
  FAILED: 'JOB_API_UNSET_READONLY_FAILED',
}

export const START = {
  REQUESTED: 'JOB_API_START_REQUESTED',
  SUCCEEDED: 'JOB_API_START_SUCCEEDED',
  FAILED: 'JOB_API_START_FAILED',
}

export const STOP = {
  REQUESTED: 'JOB_API_STOP_REQUESTED',
  SUCCEEDED: 'JOB_API_STOP_SUCCEEDED',
  FAILED: 'JOB_API_STOP_FAILED',
}

export const FETCH_JOBS = {
  REQUESTED: 'JOB_API_FETCH_JOBS_REQUESTED',
  SUCCEEDED: 'JOB_API_FETCH_JOBS_SUCCEEDED',
  FAILED: 'JOB_API_FETCH_JOBS_FAILED',
}

export const STOP_ALL = {
  REQUESTED: 'JOB_API_STOP_ALL_REQUESTED',
  SUCCEEDED: 'JOB_API_STOP_ALL_SUCCEEDED',
  FAILED: 'JOB_API_STOP_ALL_FAILED',
}

export const START_ALL = {
  REQUESTED: 'JOB_API_START_ALL_REQUESTED',
  SUCCEEDED: 'JOB_API_START_ALL_SUCCEEDED',
  FAILED: 'JOB_API_START_ALL_FAILED',
}

export const CHANGE_CONTAINER = {
  REQUESTED: 'JOB_API_CHANGE_CONTAINER_REQUESTED',
  SUCCEEDED: 'JOB_API_CHANGE_CONTAINER_SUCCEEDED',
  FAILED: 'JOB_API_CHANGE_CONTAINER_FAILED',
}

export const OPEN_EDITOR_DIALOG_TO_EDIT = {
  REQUESTED: 'JOB_API_OPEN_EDITOR_DIALOG_TO_EDIT_REQUESTED',
  SUCCEEDED: 'JOB_API_OPEN_EDITOR_DIALOG_TO_EDIT_SUCCEEDED',
  FAILED: 'JOB_API_OPEN_EDITOR_DIALOG_TO_EDIT_FAILED',
}
