export const START = 'JOB_START'
export const STOP  = 'JOB_STOP'
export const DISABLE = 'JOB_DISABLE'
export const ENABLE  = 'JOB_ENABLE'
export const ENTER_TRANSITION = 'JOB_ENTER_TRANSITION'
export const EXIT_TRANSITION  = 'JOB_EXIT_TRANSITION'
export const REMOVE = 'JOB_REMOVE'
export const SORT = 'JOB_SORT'
export const FILTER = 'JOB_FILTER'
export const CHANGE_PAGE_OFFSET = 'JOB_CHANGE_PAGE_OFFSET'

export const OPEN_CONFIG_DIALOG = 'JOB_OPEN_CONFIG_DIALOG'
export const CLOSE_CONFIG_DIALOG = 'JOB_SET_CONFIG_DIALOG'
export const SET_CONFIG_DIALOG_EDITOR = 'JOB_SET_CONFIG_DIALOG_EDITOR'

export const FETCH = {
  REQUEST: 'JOB_FETCH_REQUEST',
  SUCCESS: 'JOB_FETCH_SUCCESS',
  FAILURE: 'JOB_FETCH_FAILURE',
}

