/** for job item, api related */
export const START = 'JOB_START'
export const STOP  = 'JOB_STOP'
export const STOP_ALL = 'JOB_STOP_ALL'
export const START_ALL = 'JOB_START_ALL'
export const SET_READONLY = 'JOB_READONLY'
export const UNSET_READONLY  = 'UNSET_READONLY'

export const CREATE = 'JOB_CREATE'

export const REMOVE = 'JOB_REMOVE'
export const UPDATE = 'JOB_UPDATE'

/** for job item */
export const START_SWITCHING = 'JOB_START_SWITCHING'
export const END_SWITCHING = 'JOB_END_SWITCHING'

/** for sorter, filter, paginator */
export const SORT = 'JOB_SORT'
export const FILTER = 'JOB_FILTER'
export const CHANGE_PAGE_OFFSET = 'JOB_CHANGE_PAGE_OFFSET'

/** for dialogs, snackbar */
export const OPEN_EDITOR_DIALOG_TO_EDIT = 'JOB_OPEN_EDITOR_DIALOG_TO_EDIT'
export const OPEN_EDITOR_DIALOG_TO_CREATE = 'JOB_OPEN_EDITOR_DIALOG_TO_CREATE'
export const CLOSE_EDITOR_DIALOG = 'JOB_CLOSE_EDITOR_DIALOG'
export const OPEN_CONFIRM_DIALOG_TO_REMOVE = 'JOB_OPEN_CONFIRM_DIALOG_TO_REMOVE'
export const OPEN_CONFIRM_DIALOG_TO_ACTION_ALL = 'JOB_OPEN_CONFIRM_DIALOG_TO_ACTION_ALL'
export const CLOSE_CONFIRM_DIALOG = 'JOB_CLOSE_CONFIRM_DIALOG'
export const OPEN_ERROR_SNACKBAR = 'JOB_OPEN_ERROR_SNACKBAR'
export const OPEN_INFO_SNACKBAR = 'JOB_OPEN_INFO_SNACKBAR'
export const CLOSE_SNACKBAR = 'JOB_CLOSE_SNACKBAR'

/** api calls for job item */
export const API_FETCH_ALL = {
  SUCCEEDED: 'JOB_API_FETCH_ALL_SUCCEEDED',
  FAILED: 'JOB_API_FETCH_ALL_FAILED',
}

export const API_CREATE = {
  SUCCEEDED: 'JOB_API_CREATE_SUCCEEDED',
  FAILED: 'JOB_API_CREATE_FAILED',
}

export const API_REMOVE = {
  SUCCEEDED: 'JOB_API_REMOVE_SUCCEEDED',
  FAILED: 'JOB_API_REMOVE_FAILED',
}

export const API_FETCH_CONFIG = { /** fetch config only (no client specific props) */
  SUCCEEDED: 'JOB_API_FETCH_CONFIG_SUCCEEDED',
  FAILED: 'JOB_API_FETCH_CONFIG_FAILED',
}

export const API_UPDATE = {
  SUCCEEDED: 'JOB_API_UPDATE_SUCCEEDED',
  FAILED: 'JOB_API_UPDATE_FAILED',
}

export const API_SET_READONLY = {
  SUCCEEDED: 'JOB_API_SET_READONLY_SUCCEEDED',
  FAILED: 'JOB_API_SET_READONLY_FAILED',
}

export const API_UNSET_READONLY = {
  SUCCEEDED: 'JOB_API_UNSET_READONLY_SUCCEEDED',
  FAILED: 'JOB_API_UNSET_READONLY_FAILED',
}

export const API_START = {
  SUCCEEDED: 'JOB_START_SUCCEEDED',
  FAILED: 'JOB_START_FAILED',
}

export const API_STOP = {
  SUCCEEDED: 'JOB_STOP_SUCCEEDED',
  FAILED: 'JOB_STOP_FAILED',
}
